version: '3.3'
services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes: 
      - ./web:/var/www/html
    ports:
      - "${APACHE_AYEDD_PORT}:80"
    container_name: AYEDD
    # restart: always
    networks: 
      - network1
    environment:
      - PHP_IP_ADDRESS=${PHP_IP_ADDRESS}

  mysql:
    image: mysql:${MYSQL_VERSION}
    # restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./mysql/:/var/lib/mysql
    ports:
      - "${MYSQL_PORT}:3306"
    container_name: mysql_server
    networks:
      - network1

  phpmyadmin:
    image: phpmyadmin:${PHPMYADMIN_VERSION}
    # restart: always
    environment:
      PMA_HOST: mysql
    ports:
      - "${PHPMYADMIN_PORT}:80"
    depends_on:
      - mysql
    networks:
      - network1

networks:
  network1:
    driver: bridge
